services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
    command: sleep infinity
    depends_on:
      - mongodb
      - redis
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
